### ISSUE TITLE
[ENH] Pass "fit_args" to AutoARIMA

### ISSUE THREAD

**Issue by jasmineliaw** [sktime/sktime#3687] opened 2022-11-01 04:32 UTC
**Is your feature request related to a problem? Please describe.**
Currently it doesn't allow to specify the fit parameters from `statsmodels.tsa.arima.model.ARIMA.fit` in AutoARIMA. It will be useful if we can pass in the "fit_args" to the underlying statsmodels estimator.

![image](https://user-images.githubusercontent.com/93530957/199184780-28d6b00c-3e46-47bb-b913-f241098758a7.png)
Reference: 
https://alkaline-ml.com/pmdarima/modules/generated/pmdarima.arima.AutoARIMA.html#pmdarima.arima.AutoARIMA.fit

Supported "fit_args" from `statsmodels.tsa.arima.model.ARIMA.fit` can be found at:
https://www.statsmodels.org/devel/generated/statsmodels.tsa.arima.model.ARIMA.fit.html#statsmodels.tsa.arima.model.ARIMA.fit

For example, specifying "method" is extremely helpful to improve the performance. 
Refer to this [post](https://github.com/statsmodels/statsmodels/issues/5326) and [inline comment](https://github.com/statsmodels/statsmodels/blob/main/statsmodels/tsa/arima/model.py#L315) from statsmodels that mentioned the "innovations" algorithm could speed up the fit process.

**Comment by fkiraly** [comment] 2022-11-05 14:41
I think this is a duplicate of good first issue
https://github.com/sktime/sktime/issues/2344

Would appreciate your help with that, @jasmineliaw.

A recipe is contained in the issue 2344.

**Closed by fkiraly** 2022-11-05 14:41 UTC
Labels: module:forecasting, enhancement
