### ISSUE TITLE
[BUG] Errors when using the recursive strategy in make_reduction when forecasting panel data

### ISSUE THREAD

**Issue by wregter** [sktime/sktime#3316] opened 2022-08-22 17:08 UTC
**Describe the bug**
 I experience errors when using panel data and the recursive strategy in make_reduction. I would like to use scikit-learn regressors to perform global forecasting on panel data but the predict method is giving me errors that I do not know how to solve.

Side note: in the reproducible code I set the multiindex to integer values because otherwise this also produces an error.

**To Reproduce**

```python
<
import pandas as pd
import numpy as np
from sktime.utils._testing.hierarchical import _bottom_hier_datagen
from sktime.forecasting.compose import make_reduction
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.forecasting.base import ForecastingHorizon
from sklearn.linear_model import LinearRegression
from sktime.datatypes import check_raise

y = _bottom_hier_datagen(no_levels=1)
check_raise(y, mtype="pd-multiindex", scitype="Panel")

date_length = y.index.get_level_values(1).shape[0]
level_length = y.index.get_level_values(0).shape[0]
y = y.set_index(y.index.set_levels(np.arange(date_length), level=1))
y = y.set_index(y.index.set_levels(np.arange(level_length), level=0))

y_train, y_test = temporal_train_test_split(y, test_size=5)

forecaster = make_reduction(LinearRegression(), strategy='recursive')
horizon = pd.unique(y_test.index.get_level_values(1))
fh = ForecastingHorizon(horizon, is_relative=False)
forecaster.fit(y_train, fh=fh)
y_pred = forecaster.predict()
>
```

Error message preview:

TypeError                                 Traceback (most recent call last)
c:\Users\WREGTE16\Documents\GitHub\nl_sales_forecast\testing\a.ipynb Cell 1 in <cell line: 24>()
     [22](vscode-notebook-cell:/c%3A/Users/WREGTE16/Documents/GitHub/nl_sales_forecast/testing/a.ipynb#W0sZmlsZQ%3D%3D?line=21) fh = ForecastingHorizon(horizon, is_relative=False)
     [23](vscode-notebook-cell:/c%3A/Users/WREGTE16/Documents/GitHub/nl_sales_forecast/testing/a.ipynb#W0sZmlsZQ%3D%3D?line=22) forecaster.fit(y_train, fh=fh)
---> [24](vscode-notebook-cell:/c%3A/Users/WREGTE16/Documents/GitHub/nl_sales_forecast/testing/a.ipynb#W0sZmlsZQ%3D%3D?line=23) y_pred = forecaster.predict()

File c:\Users\WREGTE16\Miniconda3\envs\forecasting\lib\site-packages\sktime\forecasting\base\_base.py:331, in BaseForecaster.predict(self, fh, X)
    328     y_pred = self._vectorize("predict", X=X_inner, fh=fh)
    330 # convert to output mtype, identical with last y mtype seen
--> 331 y_out = convert_to(
    332     y_pred,
    333     self._y_mtype_last_seen,
    334     store=self._converter_store_y,
    335     store_behaviour="freeze",
    336 )
    338 return y_out

File c:\Users\WREGTE16\Miniconda3\envs\forecasting\lib\site-packages\sktime\datatypes\_convert.py:241, in convert_to(obj, to_type, as_scitype, store, store_behaviour)
    238     as_scitype = mtype_to_scitype(to_type)
    240 # now further narrow down as_scitype by inference from the obj
--> 241 from_type = infer_mtype(obj=obj, as_scitype=as_scitype)
    242 as_scitype = mtype_to_scitype(from_type)
    244 # if to_type is a list, we do the following:
    245 # if on the list, then don't do a conversion (convert to from_type)
...
df-list: obj must be list of pd.DataFrame, found <class 'pandas.core.series.Series'>
numpy3D: obj must be a numpy.ndarray, found <class 'pandas.core.series.Series'>
pd-multiindex: obj must be a pd.DataFrame, found <class 'pandas.core.series.Series'>
nested_univ: obj must be a pd.DataFrame, found <class 'pandas.core.series.Series'>

**Expected behavior**

I would expect this code to perform a global forecast over all levels in the panel dataset, as the make_reduction strategy is set to 'recursive' which has 'pd-multiindex' as y_inner_mtype.

**Additional context**

**Versions**
<details>

System:
    python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
executable: c:\Users\WREGTE16\Miniconda3\envs\forecasting\python.exe
   machine: Windows-10-10.0.19044-SP0

Python dependencies:
          pip: 22.1.2
   setuptools: 61.2.0
      sklearn: 1.1.2
       sktime: 0.13.1
  statsmodels: 0.13.2
        numpy: 1.22.4
        scipy: 1.8.1
       pandas: 1.4.3
   matplotlib: 3.5.3
       joblib: 1.1.0
        numba: 0.56.0
     pmdarima: None
      tsfresh: None

</details>

**Comment by fkiraly** [comment] 2022-08-22 17:16
@danbartl, FYI - any ideas?

It looks like the output is not a hierarchical data frame, but a pandas Series - that looks wrong.

**Comment by fkiraly** [comment] 2022-08-22 17:19
we need to add tests for this, too

**Comment by fkiraly** [comment] 2022-08-22 21:14
reason this was not detected is an oversight in the test suite: it collects all estimator classes (e.g., forecasters) but discards all starting in underscore `_` (assuming these are base or abstract)
https://github.com/alan-turing-institute/sktime/issues/3320

This probably means that bugs have crept in in recent refactors, and the test suite did not cover regression.

**Comment by fkiraly** [comment] 2022-08-22 21:32
reason for test failure is probably that this is not done correctly:
https://github.com/alan-turing-institute/sktime/issues/2460
I suspect we currently do not test hierarchical scenarios for forecasters that claim to handle them genuinely.

That needs to be addressed in the tests.

**Comment by fkiraly** [comment] 2022-08-23 15:53
Tests are fixed now and correctly pick up this issue. Will temporarily fix this (forcing local pooling) via #3326.

Prototype on how we can easily switch between global and local pooling is in #3327 (though that is direct reduction).

**Comment by fkiraly** [comment] 2022-08-24 17:56
@wregter, many apologies again for this, the tests did not catch the bug.

I coded up a recursive strategy now along the newer prototype design, hope this satisfies your requirements:
https://github.com/alan-turing-institute/sktime/pull/3333
still experimental, but perhaps what you were looking for - and feedback is appreciated!
(any feedback here, please: https://github.com/alan-turing-institute/sktime/issues/3224)

**Comment by fkiraly** [comment] 2022-09-15 19:01
@fkiraly, update: I no longer get the error on current `main`, windows and 3.8.12.
Not sure what fixed it? I don't remember creating a direct fix.

**Closed** 2022-10-26 09:01 UTC
Labels: bug, module:forecasting
