### ISSUE TITLE
[BUG] `model_evaluation.evaluate` fails for `statsmodels` forecasters with exogenous features

### ISSUE THREAD

**Issue by adoherty21** [sktime/sktime#3830] opened 2022-11-23 14:21 UTC
**Describe the bug**

model_evaluation.evaluate creates X_test containing both train and test samples.  For statsmodels models with exogenous features X_test length must equal the forecast horizon and therefore this currently throws the error:

`ValueError: Provided exogenous values are not of the appropriate shape.`

This bug occurs for UnobservedComponents and SARIMAX.

The root cause of the bug is in the `_split` function:
https://github.com/sktime/sktime/blob/a5f824a5fff1c3fc1babd3f34b94c5055ec040b0/sktime/forecasting/model_evaluation/_functions.py#L60

This could be modified to 'X.iloc[test].sort_index()' for statsmodels models with exogenous features or alternatively by filtering X here:
https://github.com/sktime/sktime/blob/a5f824a5fff1c3fc1babd3f34b94c5055ec040b0/sktime/forecasting/base/adapters/_statsmodels.py#L104

**To Reproduce**

```python
from sktime.datasets import load_longley
from sktime.forecasting.structural import UnobservedComponents
from sktime.forecasting.model_evaluation import evaluate
from sktime.forecasting.model_selection import SlidingWindowSplitter

y, X = load_longley()

forecaster = UnobservedComponents(level='local linear trend')

cv = SlidingWindowSplitter(fh=[1,2,3],
                           window_length = 4,
                           step_length = 1)

results = evaluate(
        forecaster=forecaster, y=y, X = X,
        cv=cv, strategy='refit', return_data=True,
        error_score = 'raise'
        )
```

**Versions**

System:
python: 3.8.12 (default, Nov 20 2022, 10:50:06)  [Clang 14.0.0 (clang-1400.0.29.202)]
machine: macOS-13.0.1-arm64-arm-64bit

Python dependencies:
          pip: 21.2
   setuptools: 63.1.0
      sklearn: 1.1.3
       sktime: 0.14.0
  statsmodels: 0.13.5
        numpy: 1.22.0
        scipy: 1.9.3
       pandas: 1.4.1
   matplotlib: 3.6.2
       joblib: 1.2.0
        numba: 0.56.4
     pmdarima: None
      tsfresh: None

**Comment by miraep8** [comment] 2022-12-06 20:10
Thank you for raising this issue!  

I think the original reason that we have  `X.iloc[test_plus_train].sort_index()` is due to certain transformers which effectively trim the input for example `Differencer`. It is however not the most elegant solution.

In the short term I am leaning towards your suggestion solution of filtering X within the `statsmodel` wrapper class (as this won't cause the other issue again, but should fix yours.  

However in the long term I think that this is connected to another issue/conversation on how to solve this underlying issue #2880  

Would you be interested in making the PR to solve this issue?  I think you did a good job identifying the likely cause.   If not we can work together to resolve it.

**Comment by adoherty21** [comment] 2022-12-06 22:00
Thanks for your response.  

I will happily make the PR to solve the issue by modifying the `statsmodels` wrapper class.  Would you mind if I add you as a reviewer on the PR?

**Comment by miraep8** [comment] 2022-12-08 15:44
@adoherty21  - certainly!  I would be happy to take a look at it!

**Comment by fkiraly** [comment] 2022-12-21 18:44
@adoherty21, @miraep8, I think this is a "consequence" duplicate of this bug? https://github.com/sktime/sktime/issues/3670

**Closed** 2022-12-31 11:49 UTC
Labels: bug, module:forecasting
