### ISSUE TITLE
[BUG] Error when fitting TBATS

### ISSUE THREAD

**Issue by nervozny** [sktime/sktime#4626] opened 2023-05-19 22:25 UTC
I get a "TypeError: __init__() got an unexpected keyword argument 'seasonal_periods'" when trying to fit a TBATS model.

**To Reproduce**

```python
from sktime.datasets import load_airline
from sktime.forecasting.tbats import TBATS
y = load_airline()
forecaster = TBATS(  
    use_box_cox=False,
    use_trend=False,
    use_damped_trend=False,
    sp=12,
    use_arma_errors=False,
    n_jobs=1)
forecaster.fit(y)
```

**Expected behavior**
Fit the model

**Additional context**
I have been successfully working with the model for a couple of days, and then this error occurred. I created a new virtual environment and tried different Python versions, but without success so far.

**Versions**
<details>
System:
    python: 3.9.13 (main, Oct 13 2022, 21:23:06) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\alex\anaconda3\envs\env1\python.exe
   machine: Windows-10-10.0.22621-SP0

Python dependencies:
          pip: 23.0.1
       sktime: 0.18.0
      sklearn: 1.2.2
        numpy: 1.24.3
        scipy: 1.10.1
       pandas: 1.5.3
   matplotlib: 3.5.1
       joblib: 1.2.0
  statsmodels: 0.13.5
        numba: None
     pmdarima: 2.0.3
      tsfresh: None
   tensorflow: None
tensorflow_probability: None

</details>

**Comment by fkiraly** [comment] 2023-05-20 13:13
I cannot reproduce the bug on current ``main``,  versions as follows:

```python
Python dependencies:
          pip: 23.0.1
       sktime: current main
      sklearn: 1.2.2
        numpy: 1.24.3
        scipy: 1.10.1
       pandas: 1.5.3
   matplotlib: None
       joblib: 1.2.0
  statsmodels: 0.14.0
        numba: None
     pmdarima: 2.0.3
      tsfresh: None
   tensorflow: None
tensorflow_probability: None
```

**Comment by fkiraly** [comment] 2023-05-20 13:14
I cannot reproduce it at the 0.18.0 release tag either.

**Comment by fkiraly** [comment] 2023-05-20 13:15
hmm, the one difference in versions is in `statsmodels`, can you try upgrading `statsmodels`, @nervozny?

**Comment by nervozny** [comment] 2023-05-21 20:09
Thank you, @fkiraly. I reinstalled anaconda, created another virtual environment and the issue seems to be solved.

**Comment by fkiraly** [comment] 2023-05-21 22:53
hm, ok, probably a corrupted environment then, or an old `statsmodels` version. I suppose we can close this then.

**Closed by fkiraly** 2023-05-21 22:53 UTC
Labels: bug, module:forecasting
