### ISSUE TITLE
[DOC] Update sktime meet up google calender

### ISSUE THREAD

**Issue by shoaibkhanz** [sktime/sktime#4989] opened 2023-07-30 08:24 UTC
#### Describe the issue linked to the documentation
I believe the [google calendar](https://www.sktime.net/en/latest/get_involved/meetups.html#meetups) isnt updated with current rhythm of the meetups. 
Adding this as a issue here so that its visible.

(clarificaiton by @fkiraly: the calendar is linked from the README and associated witih the official sktime email account)

#### Suggest a potential alternative/fix
It would be helpful if its either updated or replaced with tabular format of events that I believe mostly are scheduled on Fridays/Tuesday. Certainly the preference would be to have a calendar so that anyone can add it to their calendar.

**As per Discord**

Unless otherwise stated, times are Fridays, in UTC, on sktime discord (meet in dev/meet-ups channel ⁠meet-ups)

15:00-16:00pm - collaborative coding session & community meet-up
16:00pm - regular community council meeting

workstreams:
11:00am - pipelines, pywatts
⁠pipelines-pywatts
forecasting/deep learning/pytorch - at weekly meet-up
benchmarking, tuning - at weekly meet-up
skbase - async, https://github.com/sktime/skbase

summer mentorship programme:
3pm UTC, Tue & Fri - mentee stand-up (Fri is together with community meet-up)

**Comment by fkiraly** [comment] 2023-07-30 09:29
Duplicate of #4975, but I'm closing the other issue since this one has a better description.

**Comment by fkiraly** [comment] 2023-08-20 23:36
done, this should be up to date now

**Closed by fkiraly** 2023-08-20 23:36 UTC
Labels: documentation
