### ISSUE TITLE
ValueError: frequency is missing

### ISSUE THREAD

**Issue by meetu30** [sktime/sktime#4147] opened 2023-01-25 17:59 UTC
**Describe the bug**

**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by fkiraly** [comment] 2023-01-25 19:10
looks like a posting accident? The bug report is empty.

**Comment by meetu30** [comment] 2023-01-25 19:52
Sorry,I dont know how that happened. I had described the issue. Anyway, here is the error that I am getting when the system reaches fit statement - "ValueError: frequency is missing"
Steps I am doing -  read data in a DF
train test split to train and test DFs
set date column to index and set freq to D
now pass this train data to fit() and here I get the error

To fix this issue, I did set freq, while creating index on both test and train Dfs -
train.asfreq('d').index and here is the output -
  '2021-12-30', '2021-12-31'],
              dtype='datetime64[ns]', name='wk_start', length=2192, freq='D')  --- THIS SHOWS FREQ IS SET TO DAILY DATA
But even after this statement, when i run this block -
fh = ForecastingHorizon(test.index, is_relative=False)
forecaster = ThetaForecaster(sp=12)  # monthly seasonal periodicity
forecaster.fit(train)
y_pred = forecaster.predict(fh)
mean_absolute_percentage_error(test, y_pred)
I get error at "forecaster.fit(train)" statement.
Kindly guide. TIA!

**Comment by fkiraly** [comment] 2023-01-26 19:19
Hm, could you paste a full code block, optimally with dummy data loaded from `sktime` and/or created manually?
That will help a lot with debugging, thanks!

**Comment by sbuse** [comment] 2023-07-11 13:24
I also walked into this error message. The problem for me was that i was working with a pandas dataframe instead of a series. I got my code working after converting to a series and setting the frequency.

y_train = df['y'].squeeze().asfreq(freq='D')

**Comment by fkiraly** [comment] 2023-07-11 19:02
@sbuse, can you kindly post a full bug report with code to reproduce and python environment versions?

**Comment by sbuse** [comment] 2023-07-12 09:14
I think you can close this issue, in my case the frequency wasn't set and setting it resolved the problem. This is exactly what the error message told me to do.

**Comment by fkiraly** [comment] 2023-07-12 15:55
hm, ok, thanks!

**Closed by fkiraly** 2023-07-12 15:55 UTC
Labels: bug, module:forecasting
