### ISSUE TITLE
[BUG] NaiveForecaster will fail if trained on numpy array and forecasting horizon is np.arange starting with zero

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#3177] opened 2022-08-04 16:21 UTC
**Describe the bug**
When NaiveForecaster is trained on an numpy array and forecast horizon is np.arange(0,x) it will fail with 
```python
ValueError: y_preds must be a list of pd.Series or pd.DataFrame
```
I am not sure, if in this case the execution should fail or not. However, the error message is confusing for me. Note: When training on pd.DataFrames it will not fail.

**To Reproduce**

```python
from sktime.forecasting.naive import NaiveForecaster
import numpy as np
y = np.random.random(1000)
forecaster = NaiveForecaster()
forecaster.fit(y)
forecaster.predict(np.arange(0,10))
```

The following line with a pandas DataFrame will not fail

```python
from sktime.forecasting.naive import NaiveForecaster
import numpy as np
import pandas as pd
y = pd.DataFrame(np.random.random(1000))
forecaster = NaiveForecaster()
forecaster.fit(y)
print(forecaster.predict(np.arange(0,10)))
```

**Expected behavior**
The code does not fail or the error message is more helpful

**Additional context**
It seems to be related to the NaiveForecaster since ARIMA does not have this problem. The following lines of code will not fail

```python
from sktime.forecasting.arima import ARIMA
import numpy as np
y = np.random.random(1000)
forecaster = ARIMA()
forecaster.fit(y)
forecaster.predict(np.arange(0,10))
```

**Versions**
<details>

   machine: Linux-4.15.0-159-generic-x86_64-with-glibc2.27
Python dependencies:
          pip: 21.2.4
   setuptools: 57.0.0
      sklearn: 1.0
       sktime: 0.13.0
  statsmodels: 0.12.2
        numpy: 1.22.4
        scipy: 1.7.1
       pandas: 1.3.3
   matplotlib: 3.4.3
       joblib: 1.0.1
        numba: 0.56.0
     pmdarima: 1.8.5
      tsfresh: None
</details>

**Comment by fkiraly** [comment] 2022-08-07 15:50
bug confirmed. Source is `_format_moving_cutoff_predictions` which gets non-`pandas` input from `_predict_moving_cutoff`. The latter has a wrong docstring and looks incomplete.

This may have caused by a merge error at some point in the past? In either case, the two methods of `BaseForecaster`, together with the `_update` interface, need some clean refactoring, or perhaps even a re-write.

**Comment by benHeid** [comment] 2024-03-30 22:53
Seems to be fixed. At least the code is not reproducing the error any more.

@fkiraly What is the process in these cases? Should we close it with a comment?

**Comment by fkiraly** [comment] 2024-03-31 20:44
If you'r asking about best practice:
I'd check whether there is a test covering this, and when in doubt, just add the test. If it passes, then we can consider this issue closed.

Though I'd also be fine with just closing the issue, if you say it's resolved.

**Comment by benHeid** [comment] 2024-04-01 08:51
Thanks, yes I asked about best practice :)

**Closed** 2024-04-01 16:55 UTC
Labels: bug, module:forecasting
