### ISSUE TITLE
[ENH] Allow `plot_series()` to plot prediction intervals

### ISSUE THREAD

**Issue by chillerobscuro** [sktime/sktime#3824] opened 2022-11-21 05:26 UTC
**Is your feature request related to a problem? Please describe.**
Making interval forecasts is a key feature of `sktime`, seems like there should be a simple way to plot the intervals. 

**Describe the solution you'd like**
Pass the results of `forecaster.predict_interval()` or `forecaster.predict_quantiles()`  directly to `utils.plotting.plot_series()`. This would entail adding an argument like `intervals_to_plot`. 

**Describe alternatives you've considered**
Plot by hand, like in the [forecasting example](https://www.sktime.org/en/stable/examples/01_forecasting.html). The code is as follows:
```
from sktime.utils import plotting
y_pred = forecaster.predict()
y_pred_ints = forecaster.predict_interval(coverage=.95)

fig, ax = plotting.plot_series(y, y_pred, labels=["y", "y_pred"])
ax.fill_between(
    ax.get_lines()[-1].get_xdata(),
    y_pred_ints["Coverage"][coverage]["lower"],
    y_pred_ints["Coverage"][coverage]["upper"],
    alpha=0.2,
    color=ax.get_lines()[-1].get_c(),
    label=f"{coverage}% prediction intervals",
)
ax.legend();
```
My working solution involves adding the above code to a new function `plot_interval()` in `sktime/utils/plotting.py`, which is called on `ax` if `plot_series()` receives a pandas DataFrame including either `"Coverage"` or `"Quantile"` nested keys.

**Questions**
 - How to check if the interval is included and find its value in the predicted_interval df? It could be nested under `y_pred_ints["Coverage"]` but if the df was created by `forecaster.predict_quantiles()` it may be under `y_pred_ints["Quantiles"]`. Are there any other schemas that need to be checked for/accepted? We could allow an additional descriptive argument (ie `coverage=.95`) to `plot_series()` but I think it's cleaner to only add one new argument to that function, and raise an error if we can't infer the value from what is provided.
 - How to handle the case where multiple series and/or more than one pair of upper/lower intervals are passed?

**Comment by aiwalter** [comment] 2022-11-21 11:08
related issue: https://github.com/sktime/sktime/issues/541

**Comment by fkiraly** [comment] 2022-11-21 23:41
yes, duplicate of #541.

> receives a pandas DataFrame including either "Coverage" or "Quantile" nested keys.

I think we need to be careful, in case you did not intend this: the top level is called "Coverage" or "Quantile" only in the univariate case, otherwise it is the name of the variable(s).

> How to check if the interval is included and find its value in the predicted_interval df? It could be nested under y_pred_ints["Coverage"] but if the df was created by forecaster.predict_quantiles() it may be under y_pred_ints["Quantiles"]. Are there any other schemas that need to be checked for/accepted?

I would actually make two functions, one for predictive intervals, one for predictive quantiles - these are two related but separate concepts.

> How to handle the case where multiple series and/or more than one pair of upper/lower intervals are passed?

Interesting question. I would plot different variables in different figures.
Different quantiles or coveragesfor one variable I would plot in the same figure.

**Closed** 2022-12-02 18:13 UTC
Labels: module:forecasting, enhancement
