### ISSUE TITLE
[BUG] Graphical pipeline requires `X` in `predict`

### ISSUE THREAD

**Issue by sbuse** [sktime/sktime#5830] opened 2024-01-25 11:06 UTC
**Describe the bug**
The graphical pipeline requires `X` in the prediction step if a transformation on `y` is present in the pipeline. This doesn't make too much sense because `X` has been computed in the `fit` step and can't be provided in the `fit` by the user. 

**To Reproduce**

```python
from sktime.forecasting.compose import make_reduction
from sklearn.linear_model import Ridge
from sktime.transformations.series.difference import Differencer
from sktime.transformations.series.lag import Lag
from sktime.transformations.series.impute import Imputer
from sktime.datasets import load_airline
from sktime.split import temporal_train_test_split
from sktime.pipeline import Pipeline

y = load_airline()
y_train, y_test = temporal_train_test_split(y)

forecaster = make_reduction(Ridge(), window_length=12, strategy="recursive")

pipe = Pipeline()
pipe = pipe.add_step(Differencer(lags=[1, 3]), "differencer", edges={"X": "y"})
pipe = pipe.add_step(
    forecaster, name="forecaster", edges={"X": "differencer", "y": "y"}
)
# can't pass X=y_train, at predict-time this would be X=X_pred=y_pred
pipe.fit(y=y_train)
y_pred = pipe.predict(fh=[1, 2, 3])
```
Output:
```
ValueError: `X` must be passed to `predict` if `X` is given in `fit`.
```
**Expected behavior**

The expected behavior is that `X` is also computed in the predict step similar to the fit.  

**Additional context**

I'm working with the sktime-dev installation including the changes from (https://github.com/sktime/sktime/pull/5656)

**Versions**
<details>

System:
    python: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
executable: [c:\Users\user\anaconda3\python.exe](file:///C:/Users/user/anaconda3/python.exe)
   machine: Windows-10-10.0.22621-SP0

Python dependencies:
          pip: 22.3.1
       sktime: 0.25.0
      sklearn: 1.0.2
       skbase: 0.6.1
        numpy: 1.23.5
        scipy: 1.9.3
       pandas: 1.4.4
   matplotlib: 3.6.2
       joblib: 1.1.1
        numba: 0.56.4
  statsmodels: 0.14.1
     pmdarima: 2.0.4
statsforecast: 1.7.1
      tsfresh: None
      tslearn: None
        torch: 1.13.1+cpu
   tensorflow: None
tensorflow_probability: None

</details>

**Comment by fkiraly** [comment] 2024-01-25 13:36
Is this a duplicate of https://github.com/sktime/sktime/issues/5653?

#5653 was fixed by a PR, and the fix will be released with 0.25.1 any minute now.

**Comment by fkiraly** [comment] 2024-01-25 13:37
Oh, you are claiming that #5356 does *not* fix the problem in your above case.

So we need to check whether it is the same problem or not, and if yes why the fix did not work.

FYI @benHeid

**Comment by sbuse** [comment] 2024-01-25 16:15
What I'm saying is that https://github.com/sktime/sktime/issues/5653 fixed the problem in `fit` but now there is a new bug in `predict`.

**Comment by benHeid** [comment] 2024-01-25 20:33
It is not the same bug as the one for `fit`. The problem is a bit different. The cause of this bug is that the differencer is not called during `predict` (or with no data, I am unsure), since the buffers are emptied, because of the new data. Consequently, the result of the `differencer` step is None. Which is then passed as `X` to the forecaster. I fixed this issue by not emptying the buffers if no new data are provided... 

Sidenote: I would not like to concatenate the data to the buffers. Since this would cause head ache if we want to enable global forecasting.... Since this would require to check how to concatenate, and probably also would cause that predict would then be applied to all columns.. [It is late perhaps the sidenote makes no sense...]

**Closed** 2024-02-09 16:32 UTC
Labels: bug, module:forecasting, module:base-framework
