### ISSUE TITLE
[BUG] vmdpy - if the length of list is 2n+1，the decomposition result length is 2n, while even is correct.

### ISSUE THREAD

**Issue by bigaym** [sktime/sktime#6596] opened 2023-09-10 01:46 UTC
if the length of list is 2n+1，the decomposition result length is 2n, while even is correct.
![image](https://github.com/vrcarva/vmdpy/assets/97392187/a395b7db-a443-4c17-b8b4-f85b9a7c0483)
we use 101 points but the result is 100points.
while the vmd in matlab don't have this problem.

**Comment by fkiraly** [comment] 2024-06-14 20:49
duplicate of https://github.com/sktime/sktime/issues/6602

**Closed by fkiraly** 2024-06-14 20:49 UTC
Labels: bug, lib:vmdpy
