### ISSUE TITLE
[ENH] `num_epochs` should be renamed to `n_epochs` in `SimpleRNNClassifier` and `SimpleRNNRegressor`

### ISSUE THREAD

**Issue by achieveordie** [sktime/sktime#5485] opened 2023-10-24 09:24 UTC
Currently, we take `n_epochs` in all other estimators within the `deep_learning` subpackage with the exception of `SimpleRNNClassifier`. This inconsistency should be addressed with a deprecation of the usage of `num_epochs` in favor of `n_epochs`.

**Comment by fkiraly** [comment] 2023-10-25 08:29
agree.

Not a bug though, I would classify this as an enhancement.

**Comment by aeyazadil** [comment] 2023-12-07 14:06
Is this issue open, Can you assign it to me ?

**Comment by achieveordie** [comment] 2023-12-07 14:23
Done! Welcome to sktime :)

Feel free to ask for help if you feel stuck. Thanks

**Closed** 2023-12-24 17:11 UTC
Labels: good first issue, module:classification, enhancement
