### ISSUE TITLE
[DOC] document estimator tags in read-the-docs and allow search/filter by tag(s)

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#4713] opened 2023-06-16 18:28 UTC
All `sktime` forecasters (and most likely all estimators) have tags related to different functionalities to track their capabilities or incapabilities. As far as I am aware, these are not possible to check from `sktime.net`.

For example, as a user I may want to see all `sktime` forecasters that support probabilistic predictions. After seeing that list, I may be further interested in filtering the results by the same capability for in-sample predictions.

As another example, I may want to know if the forecaster I am using has the capability of using exogenous features or not just from the documentation page.

I do not have any concrete suggestions on how to solve either of the two examples I gave above. But here are few possible ways to consider:

1. all estimator docstrings to specifically document tags, and show these (somehow) as (possibly clickable to enable search) labels in the website
2. add tags of all estimators in their respective pages (somehow) automatically by some central functionality
3. etc.

(Please edit to add/modify/remove other ways to achieve the same.)

**Comment by fkiraly** [comment] 2023-06-16 20:38
duplicate of this?
https://github.com/sktime/sktime/issues/1930

I suppose it's a good idea since we are arriving at it independently?

(we may want to merge and see which ideas are in the "symmetric difference" of the two issues and ensure they are in the one that remains?)

**Comment by fkiraly** [comment] 2023-06-16 20:39
Maybe not a duplicate, since you are suggesting to have this closer to the API docs?

**Comment by fkiraly** [comment] 2023-06-16 20:44
I also think there are three related ideas in or close to the above:

* central estimator overview like the API table of contents per module that is searchable or filterable, see #1930
* a central list of tags, per estimator, and what they can possibly be - similar to the extension templates
* for a given estimator, list what its tags and tag values are in the docs (probably only the user facing ones)

**Comment by fkiraly** [comment] 2024-08-14 10:59
This is solved by the estimator search https://github.com/sktime/sktime/pull/6147 and tags API https://github.com/sktime/sktime/pull/6289

**Closed by fkiraly** 2024-08-14 10:59 UTC
Labels: documentation
