### ISSUE TITLE
[BUG] column-vectorized forecaster predictions are in wrong order if input is `DataFrame` with non-lexicographically ordered columns

### ISSUE THREAD

**Issue by joaovitorfranco** [sktime/sktime#4683] opened 2023-06-07 21:29 UTC
Update by @fkiraly:

The minimal bug is actually in vectorization, if columns are not lexicographically ordered. This will then happen in *any* estimator.

Example code:

```python
from sktime.datasets import load_macroeconomic
from sktime.forecasting.naive import NaiveForecaster

X = load_macroeconomic()

f = NaiveForecaster()
f.fit(y=X, fh=[1, 2, 3, 4])
f.predict()
```

The bug is likely in `vectorize_est`, and possibly introduced with #4195 - FYI @hoesler.
Update to the update: indeed coming from there and introduced with #4195, but actually coming from `DataFrame.pivot`.

The interface tests do not pick this up since the return is correct from a typing perspective, with column and row indices as expected. We should therefore add a test with the `NaiveForecaster`.

---

**Describe the bug**
The method `_get_forecaster_X_prediction` in the `ForecastX` class predicts wrong values probably due to incorrect column names and order. 

**To Reproduce**
```python
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestRegressor
from sktime.datasets import load_macroeconomic
from sktime.forecasting.compose import make_reduction

from sktime.forecasting.compose import ForecastX
from sktime.forecasting.arima import AutoARIMA
from sktime.forecasting.arima import ARIMA


data = load_macroeconomic()
y = data["unemp"]
X = data.drop(columns=["unemp"])

regressor = RandomForestRegressor(random_state=42)

forecaster = make_reduction(
    regressor,
    window_length=12,
    strategy="recursive",
    pooling="global",
)

pipe = ForecastX(forecaster_X=forecaster, forecaster_y=forecaster)

pipe.fit(X=X, y=y, fh=[1,2,3,4,5])

pipe._get_forecaster_X_prediction()
```

**Expected behavior**
Comparing X with the predicted future values of X and they should be close to each other. This is not happening in this example.

**Version**
0.18.0

**Comment by fkiraly** [comment] 2023-06-07 22:14
This is odd. We had a problem with incorrectly ordered columns before - issue #3986 - and I thought we fixed it in this PR: https://github.com/sktime/sktime/pull/3987

This was definitely merged before 0.18.0. Let me have a look, as I've written the bugfix in #3987, perhaps I missed sth.

**Comment by fkiraly** [comment] 2023-06-07 22:15
confirmed on current main - this does look like permuted columns.

**Comment by fkiraly** [comment] 2023-06-07 22:31
This is not just `ForecastX` - the problem is with any forecaster that does column vectorization and does not have columns ordered lexicographically.

I think the bug was introduced in the refactor of vectorization https://github.com/sktime/sktime/pull/4195 (FYI @hoesler).

Either way, the issue sits in lines 1753 of `_base.py` in forecasting, the call of `vectorize_est` returns the predictions in the wrong order.

**Comment by fkiraly** [comment] 2023-06-07 22:59
fun fact:

this is line 599:

```python
# TODO: add test case for tuple index
```

I suspect that test case would have been important ...

**Comment by fkiraly** [comment] 2023-06-07 23:02
Found the source:

`DataFrame.pivot` orders columns lexicographically, even if they weren't lexicographically ordered pre-pivot.

That is pretty strange - is this a bug with `DataFrame.pivot`?

**Comment by fkiraly** [comment] 2023-06-07 23:05
That's kinda funny, @hoesler - you improve the code by using sth handy and fast as `DataFrame.pivot` instead of my clunky loop, and then it turns out there's a but (or unexpected behaviour) in `pivot`... some irony.

**Comment by fkiraly** [comment] 2023-06-07 23:23
Hopefully this fixes it.

**Closed** 2023-06-18 18:46 UTC
Labels: bug, module:forecasting, module:datatypes
