### ISSUE TITLE
[BUG] `feature_kind` metadata missing in gluonTS scitype causing errors in CI

### ISSUE THREAD

**Issue by Abhay-Lejith** [sktime/sktime#6860] opened 2024-07-28 14:13 UTC
**Describe the bug**

Errors in CI because the `feature_kind` metadata is not stored for the newly added gluonTS scitypes.
Example error in CI: https://github.com/sktime/sktime/actions/runs/10131002407/job/28014414057#step:10:2644

**Additional context**

FYI @shlok191 
Similar problem occurred with polars and has been resolved. 
Here is the link to comment where I have explained what needs to be done - https://github.com/sktime/sktime/issues/6815#issuecomment-2244310505
Let me know if you need any clarification.

</details>

**Comment by shlok191** [comment] 2024-07-28 19:41
@Abhay-Lejith, got it. I'll take a look at the PR and push an update. Thank you!

**Comment by fkiraly** [comment] 2024-07-28 20:46
ah, sorry, did not see this - I just also attepmted a fix here: https://github.com/sktime/sktime/pull/6861

**Comment by fkiraly** [comment] 2024-07-29 07:36
I have merged https://github.com/sktime/sktime/pull/6861 to avoid failures on main, but I do not consider this issue complete, as it just forces float on all columns. We should at least confirm whether this is intended behaviour - if not, ensure more granular returns, at least for the dfip field.

**Closed** 2024-08-18 17:29 UTC
Labels: bug, module:datatypes
