### ISSUE TITLE
[BUG] Handling of numpy2d in transformer Interface differs significantly from time series classification/clustering/regression user expectations

### ISSUE THREAD

**Issue by haskarb** [sktime/sktime#3507] opened 2022-09-29 10:35 UTC
update (@fkiraly's summary of discussion, point 14-10-2022):

see discussion below. The reported behaviour is not a bug, but a frustrated user expectation.

This stems from how 2D numpy arrays are interpreted in `sktime` transformers and forecasters, an (m, n) array is interpreted as a single time series with m time points and n variables - let's call this convention A.

@patrickzib and @TonyBagnall think this is an unnatural way to interpret 2D numpy arrays, and would rather like an (m, n) array to be interpreted as m univariate time series of equal length (number time stamps) n - let's call this convention B.

This opinion agrees with the way in which @haskarb's user expectation was frustrated.

Related issue: https://github.com/sktime/sktime/issues/2640
relation is: classifier interpret 2D numpy arrays as per convention B. Everywhere else, convention A is applied.
Issue #2640 is about the convention clash between classifiers and everywhere else.

---

**Describe the bug**
I'm performing MiniRocket tranformation on a small dataset. However there seems to be big difference in runtime.
Original repo [here](https://github.com/angus924/minirocket).

![Screenshot 2022-09-29 at 12 29 22](https://user-images.githubusercontent.com/20501023/193008290-660fd8e5-b475-40cc-92a4-eb42654e8cbc.png)

From Sktime
![Screenshot 2022-09-29 at 12 29 54](https://user-images.githubusercontent.com/20501023/193008378-e6562735-5b34-4b31-abff-5971dfb23358.png)

**To Reproduce**

```python
%%time
#original code from Angus's repo
train = np.random.rand(100,2000).astype('float32')

parameters = minirocket.fit(train)
X_training_transform = minirocket.transform(train, parameters)
```
```python
%%time
#MiniRocket from sktime
minirocket = MiniRocket()
parameters = minirocket.fit(train)

ts_transform = minirocket.transform(train)

```

**Expected behavior**
There shouldn't be so much difference in runtime. As I scale up the number of time-series, and length, this difference will become huge.

**Additional context**

**Versions**
<details>

</details>

**Comment by fkiraly** [comment] 2022-09-29 20:30
I can reproduce the 1-2min runtime with this code:

```python
import numpy as np
from sktime.transformations.panel.rocket import MiniRocket
train = np.random.rand(100, 2000).astype("float32")

t = MiniRocket()
t.fit(train)
t.transform(train)
```

Perhaps it has to do with the default parameter choice?
```python
        num_kernels=10_000,
        max_dilations_per_kernel=32,
```

**Comment by fkiraly** [comment] 2022-09-30 20:22
how odd. Well, I suppose someone needs to take it upon them to profile the runs.
Sounds like a good first issue, at least the "profile and report" part.

**Comment by fkiraly** [comment] 2022-09-30 20:24
Perhaps related to this?
https://github.com/sktime/sktime/issues/3103

We had to remove some estimators from the tests since they were leading to segfaults.

**Comment by haskarb** [comment] 2022-10-03 12:41
From the list, it mostly looks like numba part is common. I'm not quite sure, if another reason could be the _fit and _transform function?

**Comment by patrickzib** [comment] 2022-10-10 13:44
The issue is the format of `train = np.random.rand(100, 2000).astype("float32")` in combination with `_vectorize()`.

Rocket is expecting an array of shape `(100, 1, 2000)`, yet if gets an array of shape `(100, 1, 2000)`. This triggers _vectorize(), which truns it into 2000 calls of an array of shape (1,100)? E.g. the vectorize functionality seems bogus. @fkiraly:  Not sure, what why it is triggered in `fit()` anyways to split the data? This is never correct.

A fast fix for the above code is: 

```
import numpy as np
from sktime.transformations.panel.rocket import MiniRocket
train = np.random.rand(100, 2000).astype("float32")
train = train.reshape(100, 1, 2000)

t = MiniRocket()
t.fit(train)
t.transform(train)

```
E.g. reshape the array.

Now timings are within seconds:

fit done in: 0.17706
pred done in: 2.01951


Anyhow, the `_vectorize()`- method should be fixed.

**Comment by fkiraly** [comment] 2022-10-10 23:01
> E.g. the vectorize functionality seems bogus

It is currently not actual vectorization but a loop.

I was hoping initially that it could be easily turned into vectorization later, but it is a can of worms. Too late to rename the class...

**Comment by fkiraly** [comment] 2022-10-10 23:06
Regarding the above: 2D numpy arrays of shape (n, m), when passed to transformers, are interpreted as *one* (1) time series with n time stamps and m variables. So you are asking the transformer to compute transforms of 2000 univariate time series.

This is because all transformers apply to single time series and panels of time series. For interface consistency, numpy2D can only be interpreted as on of the two possible things, a single time series with n time stamps, m variables, or n univariate time series with m time stamps.

**Comment by fkiraly** [comment] 2022-10-10 23:20
with the above explanation, I would see there being neither an issue with `_vectorize` nor with `MiniRocket`. Please reopen and comment if you disagree.

We may have to explain better the data type conventions for transformers, but that's part of the current effort on writing a transformers/pipelines tutorial anyway.

**Comment by patrickzib** [comment] 2022-10-11 06:30
Sorry, have to reopen, due to two issues:

- MiniRocket has the tag "univariate-only": True. This is violated by implicit broadcasting. Shouldn't it rather throw an exception?

- As I understand it, each call to fit overwrites the state of the previous call to fit. Thus, every call to transform uses the state of the last fit. This is also not the expected/intended behavior.

**Comment by fkiraly** [comment] 2022-10-11 22:27
> MiniRocket has the tag `"univariate-only": True`. This is violated by implicit broadcasting. Shouldn't it rather throw an exception?

No, that's correct. Univariate estimators are always broadcast/vectorized, this tag tells whether that is the case, vs genuine multivariate estimators.

Either way, even if we wanted to change that it would be a change to the base class and not to `MiniRocket`.

> As I understand it, each call to fit overwrites the state of the previous call to fit. Thus, every call to transform uses the state of the last fit. This is also not the expected/intended behavior.

It is the expected and intended behaviour.
`fit` always resets the estimator, this is a universal interface convention of `sktime` and also one of `sklearn`.

Again, it would be a proposed change to central interfaces of the base class, nothing to do with `MiniRocket`.

**Comment by fkiraly** [comment] 2022-10-11 22:27
let me know if you think it's fine to close, given the explanation.

**Comment by patrickzib** [comment] 2022-10-12 07:38
@MatthewMiddlehurst @TonyBagnall may I ask for your opinion? Do you think that broadcasting the fit operation is a good choice? Given that the state is not stored and overwritten.

**Comment by TonyBagnall** [comment] 2022-10-12 09:08
@patrickzib I need to have a closer look at Transformations because I dont fully understand what has happened to transformers this last year. I do know that you should no longer pass data to the transformer in (n_case, series_length) format, because transformers no longer handle (n_case, series_length) in a way compatible with scikit learn type representation. 

I think this 
import numpy as np
from sktime.transformations.panel.rocket import MiniRocket
train = np.random.rand(100, 2000).astype("float32")
t = MiniRocket()
t.fit(train)
t.transform(train)

is now simply incorrect usage, and if it is used as such will create logical or runtime errors that will be very hard to detect or create incorrect results. There is no longer a distinction between "panel" and "series" data, and (n_case, series_length) is not treated as modelling multiple instances. This is a bug in my opinion. I think the classification transformer should throw an error if passed 2d numpy. I would have preferred to have kept the distinction of different behaviour, but it is all so deeply embedded in datatypes etc this seems the most practical solution to me, at least short term. Use of 2D numpy in classification was in fact introduced later (I pushed for it) simply for scikit compatibility. One option would be just to remove the option. Another would be to subtype the two types of transformer again. Neither is trivial, and for now I think an error is the best way for all panel transformers.

**Comment by patrickzib** [comment] 2022-10-12 11:37
> If it's 2000*(1,1,100) then there is a bit of a problem if the transformer needs to be fit I agree. Is it essentially calling fit 2000 times and only keeping the last variable/dimension fit for the transform?

It is calling fit 2000 times, yet. I was wrong about only keeping the last one call to fit. It keeps all of them, e.g. a vector of 2000 MiniRocket instances.

**Comment by patrickzib** [comment] 2022-10-12 11:39
>  Use of 2D numpy in classification was in fact introduced a year or so into the project. I pushed for it simply for scikit compatibility. One option would be just to remove the option. Another would be to subtype the two types of transformer again. Neither is trivial, and for now I think an error is the best way for all panel transformers.

I would very much love to have 2d numpy support, as the error reported above was due to this assumption. I am just not happy by how 2d numpy arrays are interpreted right now. As this differs significantly from scikit. Thus, my point of view is to either be 100% compatible with scikit and treat the input data the same way or not at all and throw an error...

**Comment by TonyBagnall** [comment] 2022-10-12 11:40
Can agree to keep this issue open as a bug?

**Comment by fkiraly** [comment] 2022-10-12 18:31
> I do know that you should no longer pass data to the transformer in (n_case, series_length) format, because transformers no longer handle (n_case, series_length) in a way compatible with scikit learn type representation.

Claim of "no longer compatible with sktime" is not correct, the transformer convention is *now* compatible with scikit-learn, as you would expect them to be naively applied to values of a single time series.

**Comment by fkiraly** [comment] 2022-10-12 18:32
> is now simply incorrect usage

That's not incorrect usage, the 2D numpy array is just interpreted consistently with the above, as a single time series with 2000 variables. What you mean is that it disagrees with what you would prefer it would do, but the tranformer has no way to guess that.

**Comment by fkiraly** [comment] 2022-10-12 18:33
> I think the classification transformer should throw an error if passed 2d numpy

You're basically asking for a major redesign of the transformer interface here.

There is also no such thing as a "classification transformer". There is just a transformer.

Please open a STEP with your alternative suggestion if you disagree.

**Comment by fkiraly** [comment] 2022-10-12 18:34
> It is calling fit 2000 times, yes. I was wrong about only keeping the last one call to fit. It keeps all of them, e.g. a vector of 2000 MiniRocket instances.

Yes, this statement of @patrickzib is correct, prior statements about keeping only one calletc are incorrect.

**Comment by fkiraly** [comment] 2022-10-12 18:35
> I would very much love to have 2d numpy support, as the error reported above was due to this assumption. I am just not happy by how 2d numpy arrays are interpreted right now. As this differs significantly from scikit. Thus, my point of view is to (a) either be 100% compatible with scikit and treat the input data the same way or (b) not support the scikit-style at all and throw an error...

See above, my reply to @TonyBagnall. Current convention of how 2D numpy arrays are interpreted is in line with scikit-learn.

If you disagree, please open a STEP that outlines how your preferred option would look like, explain how you would treat the series, panel, and hierarchical cases, and how you would handle deprecation, thanks.

**Comment by fkiraly** [comment] 2022-10-12 18:36
We should close this issue as the discussion has moved on to the general transformer interface and away from `MiniRocket`.

**Comment by patrickzib** [comment] 2022-10-13 05:28
> There is no bug in the sense that implemented functionality would disagree with intention/design of functionality, and none of this is specific to MiniRocket.

Sorry to disagree: the design is bad, as it differs significantly from users expectation. And thus, it is very valid to open a bug. Instead of closing this issue, I we can just rename the issue.

> Claim of "no longer compatible with sktime" is not correct, the transformer convention is now compatible with scikit-learn, as you would expect them to be naively applied to values of a single time series.

Could you please elaborate on this? Passing numpy2d to a transformer in scikit-learn does not apply boradcasting but trains a single model. Imho, there is a mismatch from user expectation.

**Comment by fkiraly** [comment] 2022-10-14 10:48
> Sorry to disagree: the design is bad, as it differs significantly from users expectation. And thus, it is very valid to open a bug. Instead of closing this issue, I we can just rename the issue.

Not a bug but a design discussion, but happy with the rename.

> Could you please elaborate on this? Passing numpy2d to a transformer in scikit-learn does not apply boradcasting but trains a single model. Imho, there is a mismatch from user expectation.

Applying a single model is the default, but `MiniRocket` does not support multivariate, so it is applied per variable.

In scikit-learn, all transformers can be applied to multivariate data afaik, but in time series that's not commonly the case. The most natural way to extend univariate transformers to multivariate is broadcast.

**Comment by fkiraly** [comment] 2022-10-14 11:55
Is this a duplicate of #2640?

**Comment by fkiraly** [comment] 2022-10-14 11:59
Actually, it's very much a deja vu. @TonyBagnall, you ended up disgengaging with discussion in #2640 and it seems like we are repeating the discussion in there, just in another issue.

Would you be so kind and reply in #2640?

**Comment by TonyBagnall** [comment] 2022-10-14 15:03
I didn't disengage, I did not see any points left open to debate, you stated that the usage for 2d numpy should be as below, that it is an either or, and you chose the forecasting route. I did not see any other questions to respond to. Obviously there is a difference in expected use case between forecasting and classification/regression/clustering. Resolving these different expectations is clearly non trivial. In the short term, I think this transformer should throw an error if passed a 2D numpy array to avoid confusing users, as it has done in this example. The error message could describe your solution below. 


What will work with 2D numpy as you intend:
any classifier in sktime
including a ClassifierPipeline with any transformer and any classifier in it
including pipelines constructed with dunder methods *
The one case that doesn't work is using sklearn (not sktime) pipelines with sktime transformers if you are passing panel data.
Or, transformers in isolation.

**Comment by fkiraly** [comment] 2022-10-18 12:24
> In the short term, I think this transformer should throw an error if passed a 2D numpy array to avoid confusing users, as it has done in this example. The error message could describe your solution below.

This would break all univariate pipelines of transformers and forecasters with numpy input.

Not a good solution.

Overall, please write a STEP where you outline how precisely you want things changed and how this would affect the various modules, how you would deal with deprecation, etc.
Or, if yon don't, please accept that we won't change things ad-hoc to satisfy some local preferences because we are going to break other things (see above).

**Comment by patrickzib** [comment] 2022-10-18 14:40
I am not sure if I can follow the discussion. 

Thus, to my understanding: 

- if Rocket (or any other transformer) is used in **forecasting** with a **numpy2d** array, it should be interpreted as a single time series. 
- But if Rocket is used in classification with a numpy2d array, it should best be interpreted as a multiple univariate time series, which this bug-report comes from.

Did I get that right?

And the problem, we are facing, is that the forecasting route was used for both use cases as of now?

**Comment by fkiraly** [comment] 2022-10-19 06:25
> Did I get that right?

No, because you are imprecise at one very crucial point: you need to refer to *estimators* (e.g., transformer, forecaster), not *estimators used in a specific context* (e.g., transformer used in forecasting).

Estimators do not know their usage context (e.g., am I using a transformer for forecasting or classification), as that would violate the Law of Demeter. It may make conceptual sense to you, but it does not make technical/architectural sense.

It's like wanting a washing machine with one button that washes or dries, depending on what the user is currently thinking (intention to wash or intention to dry).

**Comment by patrickzib** [comment] 2022-10-19 06:37
That is exactly what I said and implied, @fkiraly.

**Comment by fkiraly** [comment] 2023-10-19 10:41
discussion is stale, closing

**Closed by fkiraly** 2023-10-19 10:41 UTC
Labels: API design, module:transformations
