### ISSUE TITLE
[BUG] TBATS docstring example does not run

### ISSUE THREAD

**Issue by josebaezmedina** [sktime/sktime#6291] opened 2024-04-12 17:58 UTC
The example for TBATS  from the documentation does not work.

```python
from sktime.datasets import load_airline
from sktime.forecasting.tbats import TBATS
y = load_airline()
forecaster = TBATS(  
    use_box_cox=False,
    use_trend=False,
    use_damped_trend=False,
    sp=12,
    use_arma_errors=False,
    n_jobs=1)
forecaster.fit(y)  
y_pred = forecaster.predict(fh=[1,2,3])  
```

**Expected behavior**
predictions from the time series

**I am getting:**
TypeError: _TbatsAdapter.__init__() got an unexpected keyword argument 'seasonal_periods'

**Comment by fkiraly** [comment] 2024-04-12 21:09
Thanks for reporting.
Could you kindly list your package versions, as described in the "new issue" template?

I've also added a test with `sp` parameter to see if something comes up there:
https://github.com/sktime/sktime/pull/6292

**Comment by fkiraly** [comment] 2024-04-12 23:23
@josebaezmedina, the tests in https://github.com/sktime/sktime/pull/6292 seem to run with the example above.

Possibly it is an issue with incompatible package versions in your environment?

Would appreciate package versions.

**Comment by fr1ll** [comment] 2024-07-13 22:15
@josebaezmedina- I also tested this function and it runs.

Relevant package versions:
- python=3.12.4
- sktime=0.31.0
- tbats=1.1.3

**Comment by fkiraly** [comment] 2024-07-14 16:39
Also tested and runs - might be a specific version combination, in any case error cannot be reproduced. Closing due to to lack of updates.

**Closed by fkiraly** 2024-07-14 16:39 UTC
Labels: bug, module:forecasting
