### ISSUE TITLE
[GOV] Remove NumFOCUS affiliation

### ISSUE THREAD

**Issue by aiwalter** [sktime/sktime#4201] opened 2023-02-04 19:44 UTC
update by @fkiraly moderating - for more context, see below.

Martin has (as former member of the community council at the time the letter refers to!) contributed himself fundamentally to the deteriorated situation with NumFOCUS.
This post (without him being too explicit in public) tries to construct a distorting, harmful and blaming narrative, by subtext.

Martin is no longer a member of the sktime governing bodies, and is now trying to drive a wedge into the community, after hijacking a number of digital social channels of sktime, including the slack (to which he directs people below).

For these actions, he has been permanently banned from sktime digital channels.

Original message by Martin below, for reference.

---

NumFOCUS has communicated to the community that it has decided to remove `sktime` as an affiliated project. Letter below. Kindly asking to update the docs.

[Letter to the sktime community.pdf](https://github.com/sktime/sktime/files/10609517/Letter.to.the.sktime.community.pdf)

**Comment by juanitorduz** [comment] 2023-02-06 01:04
Hey! I do not know what happened (and I do not wanna bring any further discussion), I just want to say that this makes me very sad both as a user and a contributor 😞 . I hope the project recovers from this.

**Comment by aiwalter** [comment] 2023-02-06 08:59
@juanitorduz thx for your comment, pls follow the Slack channel for further announcements of the fork

**Comment by fkiraly** [comment] 2023-02-06 20:57
From my perspective: Martin Walter and a group of contributors caused this.

This goes back to the grant which sktime was awarded, approx 1 million dollars worth.
A group of contributors around Tony Bagnall worked to remove the money from strategic control of sktime see the minutes here:
https://github.com/sktime/community-org/blob/main/community_council/previous_meetings/20220531-meeting.md
minutes point 4 and 5.

A group of contributors have since tried to evade sktime governance mechanisms trying to ensure strategic governance of the sktime gommunity. This has led to mobbing, trolling of moderators or anyone who as opposed, attacking trust in governance in sktime and attempting to dismantle governance as a whole.

@aiwalter has been in particular most active here by:

* trying to dismantle independence of the code of conduct committee https://github.com/sktime/sktime/issues/3865
* pulling in NumFOCUS, in Dec 2022, when Tony Bagnall and Martin Walter raised a complaint about "breakdown of governance". This was shortly before the deadline sktime would have reached sponsored status with NumFOCUS.
*  Continued escalation then indeed painted such a vivid picture of "breakdown of govnernance" that NumFOCUS decided to pull the plug.

Key points of evidence for what I say above:

* the confirmed minutes, as linked above, see points 4 and 5 where spending of the money on hiring and positions was discussed
* the lack of any discussion in sktime governing bodies on how to spend the 1 million dollar. That they were awarded can be checked here: https://gow.epsrc.ukri.org/NGBOViewGrant.aspx?GrantRef=EP/W030756/1
The money is currently being controlled by Tony Bagnall, who has (so far) not given the sktime community (as represented by its governance mechanisms until Dec 2022) any substantial role in how it is being used.

The "noise" that can be seen here is part of an ongoing attempt around the group to take control of the remaining sktime assets. NumFOCUS has unfortunately decided to not get involved (instead of, say, clearly saying which future for sktime they support).

**Comment by fkiraly** [comment] 2023-02-06 21:00
> pls follow the Slack channel for further announcements of the fork

the sktime slack is one of the digital assets that Martin Walter has taken over, violating sktime governance statutes.

Evidence: aiwalter removed himself here from the project. https://github.com/sktime/sktime/pull/4153

But he is an admin of the slack (as can be checked) and refuses to hand it over to a core developer. He speaks about an intended fork, and is clearly part of the intended fork.

**Comment by fkiraly** [comment] 2023-02-06 21:04
Another piece of evidence: Martin driving the narrative above, posting the letter from NumFOCUS without context - instead of trying to move towards reconciliation.

This is clearly a destructive action.

**Comment by fkiraly** [comment] 2023-02-06 21:27
I will update the affiliation but I also don't want any more of this harassment prominently visible in the public spaces of sktime. Therefore I will close this issue.

**Closed by fkiraly** 2023-02-06 21:27 UTC
Labels: enhancement
