### ISSUE TITLE
[ENH] Initial centroid guess for kmeans

### ISSUE THREAD

**Issue by Alex-JG3** [sktime/sktime#4863] opened 2023-07-10 16:02 UTC
This package is great, thanks for all the hard work.

**Is your feature request related to a problem?**
No

**Describe the solution you'd like**

It would be nice to be able to provide the `TimeSeriesKMeans` class with an initial guess of clusters similar to `KMeans` in `sklearn`, https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html. In `sklearn` you can pass a `numpy` array representing your initial guess to the `init` argument.

This would mean updating the `init_algorithm` argument for `TimeSeriesKMeans` to accept an array containing the initial centroid guesses. The dimensions of the array would be the same as the `cluster_centers_` attribute.

Alternatively, since an array of centroids is not an algorithm, perhaps it would make more sense add a new argument called `init_centroids` instead of adding it as an option to the `init_algorithm` argument. Or, the `init_algorithm` argument could be renamed to `init` which would bring it more inline with `sklearn`.

**Comment by fkiraly** [comment] 2023-07-10 19:24
Hm, the current `TimeSeriesKMeans` is a de-novo re-implementation, so there are two approaches we could take:

1. change/extend the current `TimeSeriesKMeans`
2. build a direct `sklearn` interface that "inherits" init etc

Let us know which option you would prefer, and whether you would be helping out with this (happy to get you started with the codebase and/or open source contribs)!

### changing current `TimeSeriesKMeans` de-novo re-implementation

The new init algorithm would have to be added in `TimeSeriesLloyds` attribute `_init_algorithms` (line 209).
Adding a "fixed init" strategy should not be too difficult here.

Re renaming, we can do that and it makes sense, but we would need to go through deprecation.

The algorithm looks ownerless at the moment (needs to be confirmed) so you could make the changes you are requesting.

### direct `sklearn` interface for k-means

An alternative approach would be to write another k-means class which directly interfaces the `sklearn` one and therefore also "inherits" all parameters, algorithms, bugfixes etc.

The pattern to follow here is relatively easy imo, you can take `TimeSeriesDBSCAN` as a template here.

(side note: string-to-distance resolution from registry is missing for a number of estimators currently, incl `TimeSeriersDBSCAN`, but you can leave this for now as it is being dealt with in another PR here: https://github.com/sktime/sktime/pull/4712)

**Comment by Alex-JG3** [comment] 2023-07-11 16:40
Option 2 sounds good to me and yes I would like to help with this.

I see the dbscan python file https://github.com/sktime/sktime/blob/main/sktime/clustering/dbscan.py.

Would you like this as a new class in https://github.com/sktime/sktime/blob/main/sktime/clustering/k_means.py or would like it to replace the current one?

if you would like a new class, what should the new class be called?

**Comment by fkiraly** [comment] 2023-07-11 17:24
> Option 2 sounds good to me and yes I would like to help with this.

Excellent, much appreciated!

> Would you like this ...

For reasons of not breaking anything for our users, we cannot replace or move the current class, at least not right away. I would also recommend to avoid modifying the existing file due to it being coupled to the Lloyds class and `numba` (via the `distances` module).

Now, this results in a slightly hard problem to come up with a non-confusing solution that can be a combination of naming a new file, potentially introducing a folder, and potentially renaming with deprecation.

Thoughts, I cannot come up with a solution that sounds "obvious":
* perhaps a folder `k_means` which contains the old and the new file (private) and an `__init__` which exports all classes?
* perhaps name it `TimeSeriesKMeansSklearn`?
    * Noting that `tslearn` also has a time series k-means (confusingly, of the same name as the `sktime` native class), this could later be a `TimeSeriesKMeansTslearn`? On a side note, an example for `tslearn` interface pattern is in `kernel_k_means.py`, also copy-pasteable (probably should be a proper adapter instead).

FYI, `sktime`'s policy is currently closer to the "library" paradigm than to sklearn's "opinionated selection" paradigm, especially since there's less of a canon in the time series space. See here:
https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-inclusion-guidelines

Another example of this are the multiple SARIMAX algorithms we have - `statsmodels`, `statsforecast`, and `pmdarima`. All of these are popular with people having strong opinions on one vs the other, so why play the arbiter instead of just facilitating use and comparison?

**Comment by fkiraly** [comment] 2023-08-01 14:50
@Alex-JG3, I looked into the code, and the following should be possible in :

to `init_algorithm` of `TimeSeriesKMeans`, pass a function that returns a 3D `np.array`, (n_instance, n_vars, n_timepoints), these are `n_instance` cluster centers.

What I think *should* be done:

* allow 3D `np.array` as `init_algorithm`
* in `__init__` of `TimeSeriesLloyds`, catch `np.array` and replace by this function
* update the docstring that this is possible.

**Comment by Alex-JG3** [comment] 2023-08-01 17:49
@fkiraly, yes I see what you mean. I will open a new pull request and try and make these changes.

**Comment by fkiraly** [comment] 2023-08-06 13:34
@Alex-JG3, looks like we have two PR that would fix this!

* yours here, #5001
* I also started a mini-project interfacing all of `tslearn` after I had been refactoring adapter boilerplate - turned out the refactor made it really easy. PR https://github.com/sktime/sktime/pull/5037 adds an interface to the `tslearn` k-means, which does have init with an initial guess

**Closed** 2023-08-06 15:07 UTC
Labels: feature request, module:clustering, enhancement

**Comment by fkiraly** [comment] 2023-08-06 16:17
well, isn't that funny, @Alex-JG3 - now we'll have *two* clusterers that have an initial centroid guess option, as opposed to zero
